# Generated by Django 5.0.4 on 2024-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_gennie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lawyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
