# Generated by Django 5.0.4 on 2024-12-29 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_gennie', '0002_user_is_lawyer_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('lawyer_type', models.CharField(choices=[(1, 'Corporate'), (2, 'Criminal'), (3, 'Family'), (4, 'Tax'), (5, 'Immiagration'), (6, 'Intellectual Property'), (7, 'Real Estate'), (8, 'Labour'), (9, 'Entertainment'), (10, 'Other')], default=10, max_length=50)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('call_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_meta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
