# Generated by Django 5.0.4 on 2024-12-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_gennie', '0003_lawyermetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyermetadata',
            name='lawyer_type',
            field=models.IntegerField(choices=[(1, 'Corporate'), (2, 'Criminal'), (3, 'Family'), (4, 'Tax'), (5, 'Immiagration'), (6, 'Intellectual Property'), (7, 'Real Estate'), (8, 'Labour'), (9, 'Entertainment'), (10, 'General')], default=10),
        ),
    ]
